"""add category column and drop balance from debts

Revision ID: xxxx   # alembic auto-generates this
Revises: yyyy       # previous migration ID
Create Date: 2025-08-18

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'c3044d506731'
down_revision = '7b22013a9f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False))
        batch_op.drop_column('balance')
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))
        batch_op.drop_column('category')
    # ### end Alembic commands ###
