"""Create finance_settings table

Revision ID: 7b22013a9f7b
Revises: c3044d506731
Create Date: 2025-08-18 14:59:38.153190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b22013a9f7b'
down_revision = 'c3044d506731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False))
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
