"""ADDING email field on my customer 

Revision ID: e7cf10a3cbb2
Revises: d6b12dd5437c
Create Date: 2025-09-02 12:43:47.879318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7cf10a3cbb2'
down_revision = 'd6b12dd5437c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
