"""Add finance model to track business finance and new columns to track a debts last reminder and reminder count

Revision ID: 86afb6b7b756
Revises: eec570bb0072
Create Date: 2025-08-12 18:04:43.664558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86afb6b7b756'
down_revision = 'eec570bb0072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reminder_sent', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reminder_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.drop_column('reminder_count')
        batch_op.drop_column('last_reminder_sent')

    # ### end Alembic commands ###
