"""added last_verification_email_sent

Revision ID: 8cbc6ef28373
Revises: 83f19f94ecdf
Create Date: 2025-08-10 19:32:00.127634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cbc6ef28373'
down_revision = '83f19f94ecdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_verification_email_sent', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_verification_email_sent')

    # ### end Alembic commands ###
