"""Create finance_settings table

Revision ID: c3044d506731
Revises: 86afb6b7b756
Create Date: 2025-08-12 18:13:40.804037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3044d506731'
down_revision = '86afb6b7b756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('payment_due_day', sa.Integer(), nullable=True),
    sa.Column('grace_period_days', sa.Integer(), nullable=True),
    sa.Column('late_fee_type', sa.String(length=20), nullable=True),
    sa.Column('late_fee_value', sa.Float(), nullable=True),
    sa.Column('late_fee_max', sa.Float(), nullable=True),
    sa.Column('late_fee_recurring', sa.Boolean(), nullable=True),
    sa.Column('interest_enabled', sa.Boolean(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('interest_compounding', sa.String(length=20), nullable=True),
    sa.Column('reminder_before_due', sa.Boolean(), nullable=True),
    sa.Column('reminder_before_days', sa.Integer(), nullable=True),
    sa.Column('reminder_after_due', sa.Boolean(), nullable=True),
    sa.Column('reminder_after_days', sa.Integer(), nullable=True),
    sa.Column('reminder_method', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finance_settings')
    # ### end Alembic commands ###
